version: '1.0'
services:
  jupyter-notebook:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]